name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  # --- JOB 1: Build and Upload Binaries ---
  build-and-upload:
    name: Build on ${{ matrix.os }} (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false 
      matrix:
        include:
          # Linux
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary_name: query-fuse
            asset_name: query-fuse-linux-amd64.tar.gz
          
          # Mac - Intel
          - os: macos-15
            target: x86_64-apple-darwin
            binary_name: query-fuse
            asset_name: query-fuse-macos-intel.tar.gz

          # Mac - Apple Siliccon
          - os: macos-14
            target: aarch64-apple-darwin
            binary_name: query-fuse
            asset_name: query-fuse-macos-arm64.tar.gz

          # Windows
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            binary_name: query-fuse.exe
            asset_name: query-fuse-windows.zip

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build Binary
        run: cargo build --release --target ${{ matrix.target }} --verbose

      - name: Compress (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          cd target/${{ matrix.target }}/release
          tar -czf ../../../${{ matrix.asset_name }} ${{ matrix.binary_name }}
          cd ../../..

      - name: Compress (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          cd target/${{ matrix.target }}/release
          7z a ../../../${{ matrix.asset_name }} ${{ matrix.binary_name }}
          cd ../../..

      - name: Upload Binary to Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: query-fuse-*
  
  # --- JOB 2: Build and Push Docker Image ---
  push-docker-image:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/query-fuse

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}