name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-upload:
    name: Build on ${{ matrix.os }} (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # Linux
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary_name: query-fuse
            asset_name: query-fuse-linux-amd64.tar.gz
          
          # Mac - Intel
          - os: macos-13
            target: x86_64-apple-darwin
            binary_name: query-fuse
            asset_name: query-fuse-macos-intel.tar.gz

          # Mac - Apple Siliccon
          - os: macos-14
            target: aarch64-apple-darwin
            binary_name: query-fuse
            asset_name: query-fuse-macos-arm64.tar.gz

          # Windows
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            binary_name: query-fuse.exe
            asset_name: query-fuse-windows.zip

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build Binary
        run: cargo build --release --target ${{ matrix.target }} --verbose

      - name: Compress (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          cd target/${{ matrix.target }}/release
          tar -czf ../../../${{ matrix.asset_name }} ${{ matrix.binary_name }}
          cd ../../..

      - name: Compress (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          cd target/${{ matrix.target }}/release
          7z a ../../../${{ matrix.asset_name }} ${{ matrix.binary_name }}
          cd ../../..

      - name: Upload Binary to Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: query-fuse-*